# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [4]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [5]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int, delimiter = ',', skiprows = 1)
res = data[:5]
print(res)

C:\Users\222671\AppData\Local\Temp/ipykernel_16160/3608779900.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int, delimiter = ',', skiprows = 1)


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [6]:
print("Минимальное значение:","\n",np.min(data, axis=0))
print("Максимум:","\n",np.max(data, axis=0))
print('Среднее значение:', '\n', np.mean(data, axis = 0))
print('Медиана:', '\n', np.median(data, axis = 0))

Минимальное значение: 
 [38  0  1]
Максимум: 
 [    537671 2147483647         39]
Среднее значение: 
 [2.22064324e+05 2.16010017e+04 9.05528000e+00]
Медиана: 
 [2.071935e+05 4.000000e+01 9.000000e+00]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
res = data[:,1:2]
print(np.quantile(res, 0.75, axis = 0))
q_075 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.clip(data[:, 1], a_min=0, a_max=q_075)
data[:20]

[65.]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5],
       [366174,      7,      9],
       [ 74205,     20,      7],
       [504666,     65,     20],
       [ 81006,     12,      7],
       [280968,     65,     11],
       [204134,      5,      3],
       [ 18593,     35,      7],
       [ 25623,      6,      4],
       [ 65559,     24,     14],
       [ 99836,     65,      7],
       [ 87775,     65,     13],
       [425704,     40,     12]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
res = data[:, 1:2]
np.place(res, res<1, [1])
print(res)

[[60]
 [25]
 [10]
 ...
 [65]
 [ 5]
 [65]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
print(len(np.unique(data[:, :1])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [18]:
unique, counts = np.unique(data[:,2], return_counts=True)
print(f'уникальных: {len(unique)}')
dict(zip(counts, unique))

уникальных: 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [42]:
res = data[:, 2]
print(res[res<5].shape)

(9349,)


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [52]:
print(np.max(data[:, 2]//data[:, 1]))

23


C:\Users\User\AppData\Local\Temp\ipykernel_312\1719986758.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.max(data[:, 2]//data[:, 1]))


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [6]:
print(np.mean(data[np.argsort(data[:,1])][-100:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [20]:
n = 10 
index = np.random.choice(data.shape[0], n, replace=False)  
print(data[index])

[[163523     90     17]
 [ 54924    100      7]
 [349602     25      6]
 [454703     45     11]
 [393043     45     11]
 [341016     45      8]
 [125068     15      7]
 [429565      5      4]
 [173596    620     18]
 [422845     20      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [7]:
print(data[data[:,2]<np.mean(data[:,2])].shape[0]/data.shape[0]*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [16]:
ndata = np.c_[data, (data[:, 1]<=20) & (data[:,2] <= 5)]
ndata

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [9]:
#второе решение
import pandas as pd
df = pd.read_csv('minutes_n_ingredients.csv')
df
df['condition'] = np.where((df['minutes']<20) & (df['n_ingredients'] < 5), 1, 0)
df

id  minutes  n_ingredients  condition
0      127244       60             16          0
1       23891       25              7          0
2       94746       10              6          0
3       67660        5              6          0
4      157911       60             14          0
...       ...      ...            ...        ...
99995   43407       35              7          0
99996  287943       85             15          0
99997  498432       65             15          0
99998  370915        5              4          1
99999   81993      140             14          0

[100000 rows x 4 columns]

13. Выведите процент "простых" рецептов в датасете

In [17]:
simplec = ndata[ndata[:,3] == 1].shape[0]
allc = ndata.shape[0]
simplec*100/allc

9.552

In [11]:
#второе решение
print(df[df['condition']==1].shape[0]/df.shape[0]*100)

5.093


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [62]:
arr1 = data[data[:,1] < 10]
arr2 = data[(data[:,1] >= 10) & (data[:,1] < 20)]
arr3 = data[20 <= data[:,1]]
df = np.min([arr1.shape[0], arr2.shape[0], arr3.shape[0]])
res = np.array([arr1[:df], arr2[:df], arr3[:df]])
print(res.shape)
print(res)

(3, 7588, 3)
[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
